op = {
	id = "artefact_variationizer", sh = true, gr = {
    	{id = "banner", type = "slide", text = "ui_mcm_artefact_variationizer_title", size = {512, 50}, spacing = 20},

        {id = "generate", type = "check", val = 1, def = true},
        {id = "delete_artys", type = "check", val = 1, def = false},
    	{id = "debug_mode", type = "check", val = 1, def = false},
    }
}

function on_mcm_load()
    return op
end
